debug=true
spring.data.rest.detection-strategy=all
spring:
datasource:
url: jdbc:postgresql://localhost:5432/auth_db
username: postgres
password:admin
driver-class-name: org.postgresql.Driver

jpa:
hibernate:
ddl-auto: update
database-platform: org.hibernate.dialect.PostgreSQLDialect
show-sql: true