spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
keycloak.server-url=http://localhost:8180
keycloak.realm=bdcc-realm
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=1234
#########
management.health.mail.enabled=false
