etudiant.params.x=44
etudiant.params.y=11

spring.datasource.url=jdbc:postgresql://localhost:5432/etudiant_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true



# Multipart (déjà configuré)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# ========== NOUVELLE CONFIGURATION NEXTCLOUD ==========
# Type de stockage : local ou nextcloud
file.storage.type=nextcloud

# Configuration Nextcloud
nextcloud.url=http://localhost:8082
nextcloud.username=admin
nextcloud.password=admin123
nextcloud.base-path=/remote.php/dav/files/admin
nextcloud.documents-folder=enrollments

spring.cloud.discovery.enabled=true

